# Generated by Django 2.0.7 on 2021-07-10 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('replay', models.BooleanField()),
                ('Consulation_docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulation', to='docters.Docter')),
                ('consulation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
