# Generated by Django 2.0.7 on 2021-07-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docters', '0003_auto_20210713_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.TimeField()),
                ('enddate', models.TimeField()),
                ('bookedup', models.BooleanField()),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('docter_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='docters.Docter')),
            ],
        ),
    ]
